### ISSUE TITLE
autoluv: command not found

### ISSUE THREAD

**Issue by pkh106** [byalextran/autoluv#2]
Hi Alex - just wanted to thank you in advance.  i've gotten your other branch working (i think) and now trying to get "autoluv" to work.  Have all my ruby dependencies installed and now scratching my head when i'm in the autoluv folder.  Running Ubuntu 14.04

any thoughts on why this might be happening?

user@ubuntu14:~/autoluv$ autoluv
autoluv: command not found
user@ubuntu14:~/autoluv/bin$ ls
autoluv
user@ubuntu14:~/autoluv/bin$ autoluv
autoluv: command not found

**Comment by byalextran** [comment]
assuming you're in `~/autoluv/`, you need to prefix the command with a `./`. 

`./bin/autoluv schedule -c ABCDEF -f Alex -l Tran -b text -p 555-555-1212 -e email@domain.com`

[read this](http://stackoverflow.com/questions/6331075/why-do-you-need-dot-slash-before-script-name-to-run-it-in-bash) for why the `./` is needed.

**Comment by pkh106** [comment]
doh!
thanks Alex.  Got it working.
