### ISSUE TITLE
Names with spaces don't work

### ISSUE THREAD

**Issue by rufus210** [byalextran/autoluv#5]
Names with spaces (which are legally valid) break the script.  If I do:
 ./bin/autoluv schedule -c 123 -f First -l "Foo Bar"
The command that gets added to at is:
 ./bin/autoluv schedule -c 123 -f First -l Foo Bar
Which will obviously not work.  The first and last parameters should be quoted when added to at.

**Comment by byalextran** [comment]
ahh, thanks for that catch. i just pushed an update. give it a whirl and see if it fixes this issue.
